schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_name: 'ubuntu2204'
    image_version: '22.4.3'
    image_type: 'ubuntu'
    image_readme_name: 'Ubuntu2204-Readme.md'
    image_template_name: 'ubuntu-22.04.pkr.hcl'
