schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_type: 'linux'
    image_name: 'ubuntu2204'
    image_version: '22.4.0'
    image_readme_name: Ubuntu2204-Readme.md
