schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_type: 'win'
    image_name: 'windows2022'
    image_version: '2022'
    image_readme_name: Windows2022-Readme.md
