name: Trigger Ubuntu22.04 CI
run-name: Ubuntu22.04 - ${{ github.event.pull_request.title }}

on:
  pull_request_target:
    types: labeled
    paths:
    - 'images/linux/**'
  push:
    branches: 
    - main
    paths-ignore:
    - 'docs/**'
    - '.vscode'
    - 'images/linux/Ubuntu2204-Readme.md'
    - 'images/macos/**'
    - 'images/win/**'
    - 'images.CI/linux-and-win/azure-pipelines/windows*'
    - 'images.CI/macos/**'

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2204:
    uses: ./.github/workflows/linux-win-generation.yml
    with:
      image_type: 'linux'
      image_name: 'ubuntu2204'
      image_version: '22.4.0'
    secrets: inherit
