run-name: Ubuntu22.04 - ${{ (github.event.pull_request.title || 'scheduled/manual run') }}
on:
  workflow_dispatch:
    inputs:
      CUSTOM_REPOSITORY:
        description: 'Custom repository (owner/repo)'
        required: false
      CUSTOM_REPOSITORY_COMMIT_HASH:
        description: 'Commit hash'
        required: false
  push:
    branches: 
    - main
    paths-ignore:
    - 'docs/**'
    - '.vscode'
    - 'images/linux/Ubuntu2204-Readme.md'
    - 'images/macos/**'
    - 'images/win/**'
    - 'images.CI/linux-and-win/azure-pipelines/windows*'
    - 'images.CI/macos/**'

jobs:
  Ubuntu_2204:
    uses: ./.github/workflows/ubuntu-win-generation.yml
    with:
      image_name: 'ubuntu2204'
      image_version: '22.4.0'
      image_readme_name: 'Ubuntu2204-Readme.md'
      custom_repo: ${{ github.event.inputs.CUSTOM_REPOSITORY }}
      custom_repo_commit_hash: ${{ github.event.inputs.CUSTOM_REPOSITORY_COMMIT_HASH }}
    secrets: inherit
