name: Trigger Ubuntu20.04 CI
run-name: Ubuntu20.04 - ${{ github.event.pull_request.title }}

on:
  pull_request_target:
    types: labeled
    paths:
    - 'images/linux/**'

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2004:
    uses: ./.github/workflows/linux-win-generation.yml
    with:
      image_type: 'linux'
      image_name: 'ubuntu2004'
      image_version: '20.4.0'
    secrets: inherit
