name: Trigger Ubuntu22.04 CI
run-name: Ubuntu22.04 - ${{ github.event.pull_request.title }}

on:

  push:
    branches: 
    - main
    paths-ignore:
    - 'docs/**'
    - '.vscode'
    - 'images/linux/Ubuntu2204-Readme.md'
    - 'images/macos/**'
    - 'images/win/**'
    - 'images.CI/linux-and-win/azure-pipelines/windows*'
    - 'images.CI/macos/**'

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2204:
    uses: ./.github/workflows/ubuntu-win-generation.yml
    with:
      image_name: 'ubuntu2204'
      image_version: '22.4.0'
      image_type: 'ubuntu'
      image_readme_name: 'Ubuntu2204-Readme.md'
      image_template_name: 'ubuntu-22.04.pkr.hcl'
    secrets: inherit
