name: Trigger Ubuntu22.04 CI
run-name: Ubuntu22.04 - ${{ github.event.pull_request.title }}

on:

  push:
    branches: ["main"]

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2204:
    uses: ./.github/workflows/trigger-ubuntu-win-build.yml
    with:
      image_type: 'ubuntu2204'
    secrets: inherit
