name: Trigger Ubuntu22.04 CI
run-name: Ubuntu22.04 - ${{ github.event.pull_request.title }}

on:
  pull_request_target:
    types: labeled
    paths:
    - 'images/linux/**'
  push:
    branches: ["main"]

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2204:
    uses: ./.github/workflows/linux-win-generation.yml
    with:
      image_type: 'ubuntu2204'
    secrets: inherit
