name: Trigger Windows19 CI
run-name: Windows2019 - ${{ github.event.pull_request.title }}

on:
  pull_request_target:
    types: labeled
    paths:
    - 'images/win/**'

defaults:
  run:
    shell: pwsh

jobs:
  Windows_2019:
    uses: ./.github/workflows/linux-win-generation.yml
    with:
      image_type: 'win'
      image_name: 'windows2019'
      image_version: '2019'
    secrets: inherit
