name: Trigger Windows22 CI
run-name: Windows2022 - ${{ github.event.pull_request.title }}

on:
  pull_request_target:
    types: labeled
    paths:
    - 'images/win/**'

defaults:
  run:
    shell: pwsh

jobs:
  Windows_2022:
    uses: ./.github/workflows/linux-win-generation.yml
    with:
      image_type: 'win'
      image_name: 'windows2022'
      image_version: '2022'
    secrets: inherit
